Update update-vmware-tools

diff --git a/scripts/update-vmware-tools b/scripts/update-vmware-tools
--- a/scripts/update-vmware-tools
+++ b/scripts/update-vmware-tools
@@ -1,3 +1,14 @@
+#!/bin/bash
+# exit on error
+set -e
+
+# check if root
+if [ "$(whoami)" != "root" ] ; then
+    echo "please run as sudo"
+    exit;
+fi
+
+# run logic
 mkdir ~/tmp-mnt-cdrom
 sudo mount /dev/cdrom ~/tmp-mnt-cdrom
 mkdir ~/tmp-vmware-tools-install
